"""
This file includes mapping after LC changes in November 2021
"""
ADOPTED = [
    "Noncitizens",
    "Noncitizen criminals",
    # "Noncitizens (Greek law)",
    # "Noncitizens (Islamic law)",
    # "Noncitizens (Jewish law)",
    # "Noncitizens (Roman law)",
    # "Noncitizens in art",
    # "Noncitizens in literature",
    # "Noncitizens in mass media",
    # "Noncitizens in motion pictures",
    # "Noncitizens Care",
    # "Noncitizens Care Germany",
    # "Noncitizens Housing",
    # "Noncitizens Housing Great Britain",
    # "Noncitizens Medical care",
    # "Noncitizens Medical care Law and legislation",
    # "Noncitizens Medical examinations",
    # "Noncitizens Mental health",
    # "Noncitizens Political activity",
    # "Noncitizens Suffrage",
    # "Noncitizens Taxation",
    # "Noncitizens Taxation Law and legislation",
    # "Noncitizens Taxation Law and legislation Germany",
    # "Noncitizens Taxation Law and legislation United States",
    # "Noncitizens Austria",
    # "Noncitizens Belgium",
    # "Noncitizens Brazil",
    # "Noncitizens China",
    # "Noncitizens Confederate States of America",
    # "Noncitizens Egypt",
    # "Noncitizens European Union countries",
    # "Noncitizens France",
    # "Noncitizens Germany",
    # "Noncitizens Germany (West)",
    # "Noncitizens Great Britain",
    # "Noncitizens Italy",
    # "Noncitizens Japan",
    # "Noncitizens Mexico",
    # "Noncitizens Netherlands",
    # "Noncitizens Russia (Federation)",
    # "Noncitizens Spain",
    # "Noncitizens Sweden",
    # "Noncitizens Switzerland",
    # "Noncitizens Turkey",
    # "Noncitizens United States",
    # "Noncitizens United States Identification",
    # "Noncitizens United States Juvenile literature",
    "China Officials and employees, Noncitizen",
    "Church work with noncitizens",
    "Church work with noncitizens Baptists, [Catholic Church, etc.]",
    "Corporations, Foreign",
    "Deportees",
    "Drago doctrine",
    "Eminent domain (International law)",
    "Exiles",
    "Green cards",
    "Immigrants",
    "Pilgrims and pilgrimages Law and legislation",
    "Refugees",
    "Refuge (Humanitarian assistance)",
    "Repatriation",
    "Sanctuary movement",
    "Security for costs",
    "Stateless persons",
    "American property",
    "Armenian property",
    "Austrian property",
    "Belarusian property",
    "Belgian property",
    "British property",
    "Bulgarian property",
    "Burmese property",
    "Chinese property",
    "Czech property",
    "Danish property",
    "Dutch property",
    "Enemy property",
    "Farms Foreign ownership",
    "French property",
    "Hungarian property",
    "Iranian property",
    "Iraqi property",
    "Italian property",
    "Ivoirian property",
    "Japanese property",
    "Korean property",
    "Kuwaiti property",
    "Lebanese property",
    "Liberian property",
    "Libyan property",
    "Moroccan property",
    "Polish property",
    "Real property foreign ownership",
    "Refugee property",
    "Romanian property",
    "Russian property",
    "Somali property",
    "Swiss property",
    "Syrian property",
    "Venezuelan property",
    "Yemeni property",
    "Yugoslav property",
    "Zimbabwean property",
]


SPLIT = [
    ("Children of undocumented immigrants", "Children of noncitizens"),
    ("Undocumented children", "Noncitizen children"),
    ("Undocumented immigrants", "Noncitizens"),
    ("Women undocumented immigrants", "Women noncitizens"),
]

CHANGED = [
    (
        "Undocumented immigrants in literature",
        "Undocumented immigration in literature",
    ),
]
