"""
This file includes mapping after LC changes in November 2021
"""
ADOPTED = [
    "Noncitizen criminals",
    "Noncitizens (Greek law)",
    "Noncitizens (Islamic law)",
    "Noncitizens (Jewish law)",
    "Noncitizens (Roman law)",
    "Noncitizens in art",
    "Noncitizens in literature",
    "Noncitizens in mass media",
    "Noncitizens in motion pictures",
    "Noncitizens Care",
    "Noncitizens Care Germany",
    "Noncitizens Housing",
    "Noncitizens Housing Great Britain",
    "Noncitizens Medical care",
    "Noncitizens Medical care Law and legislation",
    "Noncitizens Medical examinations",
    "Noncitizens Mental health",
    "Noncitizens Political activity",
    "Noncitizens Suffrage",
    "Noncitizens Taxation",
    "Noncitizens Taxation Law and legislation",
    "Noncitizens Taxation Law and legislation Germany",
    "Noncitizens Taxation Law and legislation United States",
    "Noncitizens Austria",
    "Noncitizens Belgium",
    "Noncitizens Brazil",
    "Noncitizens China",
    "Noncitizens Confederate States of America",
    "Noncitizens Egypt",
    "Noncitizens European Union countries",
    "Noncitizens France",
    "Noncitizens Germany",
    "Noncitizens Germany (West)",
    "Noncitizens Great Britain",
    "Noncitizens Italy",
    "Noncitizens Japan",
    "Noncitizens Mexico",
    "Noncitizens Netherlands",
    "Noncitizens Russia (Federation)",
    "Noncitizens Spain",
    "Noncitizens Sweden",
    "Noncitizens Switzerland",
    "Noncitizens Turkey",
    "Noncitizens United States",
    "Noncitizens United States Identification",
    "Noncitizens United States Juvenile literature",
    "Children of undocumented immigrants Education",
    "Children of undocumented immigrants Education Law and legislation",
    "China Officials and employees, Noncitizen",
    "Church work with noncitizens",
    "Church work with noncitizens Baptists, [Catholic Church, etc.]",
    "Undocumented immigrants",
    "Undocumented immigrants in literature",
    "Undocumented immigrants Fiction",
    "Undocumented immigrants Government policy United States",
    "Undocumented immigrants United States",
    "Corporations, Foreign",
    "Deportees",
    "Drago doctrine",
    "Exiles",
    "Green cards",
    "Immigrants",
    "Pilgrims and pilgrimages Law and legislation",
    "Refugees",
    "Repatriation",
    "Security for costs",
    "Stateless persons",
]
